Hw11 draft, for help
DisasterCooper/hw_max_b_py pull request #5
Opened 2023-04-02 16:34 UTC by DisasterCooper

Привет! Используя два класса, не могу понять, как передать историю операций. Если можно, небольшую подсказку и в целом, может я (как обычно) все пытаюсь усложнить

2023-04-03 10:21 UTC, vimoro requested changes

2023-04-03 10:21 UTC, vimoro commented on my_hw_tms/hw_11_bm.py
> +        self.history_opp = list[HistoryOpp] = []  # как передать историю, не могу понять
вот тут ты наверное имел в виду аннотацию, нужно вместо = написать :
`self.history_opp: list[HistoryOpp] = []`

2023-04-03 10:21 UTC, vimoro commented on my_hw_tms/hw_11_bm.py
> +        self.history_opp.append(OperationEnum.PLUS, amount, date_time)
тут нужно создать объект HistoryOpp:
`self.history_opp.append(HistoryOpp(OperationEnum.PLUS, amount, date_time))`

2023-04-03 10:21 UTC, vimoro commented on my_hw_tms/hw_11_bm.py
> +        self.history_opp.append(OperationEnum.MINUS, amount, datetime)
и здесь:
`self.history_opp.append(HistoryOpp(OperationEnum.MINUS, amount, date_time))`

2023-04-03 10:21 UTC, vimoro commented on my_hw_tms/hw_11_bm.py
в целом очень хорошо разбил задачу на классы и определил связи и у кого какие атрибуты и методы, только подправить момент с добавлением истории, молодец👍

2023-04-03 14:32 UTC, vimoro commented on my_hw_tms/hw_11_bm.py
> +    def create_bank_acc(self, bank_acc: str, balance: float):
вот только этот метод упустила, зачем он тебе? выглядит как ненужный

2023-04-03 17:42 UTC, DisasterCooper commented on my_hw_tms/hw_11_bm.py
> +    def create_bank_acc(self, bank_acc: str, balance: float):
Хотел попробовать еще банковский аккаунт создать. А потом забыл закомментировать

2023-04-03 17:42 UTC, DisasterCooper commented on my_hw_tms/hw_11_bm.py
> +        self.history_opp = list[HistoryOpp] = []  # как передать историю, не могу понять
Да, точно, спасибо!

2023-04-25 21:09 UTC, vimoro approved these changes

2023-04-30 14:06 UTC, merged